Master_array = [
  ["The Egyptians came up with the idea of a toilet seat",False]
  ["The amount of blood a mosquito takes in an average bite could fill a water bottle",True]
  ["Cat's urine glows under a blacklight",False]
  ["Burps are contagious",False]
  ["A hippo can open its mouth wide enough to fit a 4 foot tall child inside",True]
  ["A toothpick is the object most often choked on by Americans",True]
  ["It takes a lobster approximately seven years to grow to be one pound",True]
  ["A woman once gave birth to a baby with naturally blue hair",False]
  ["Toilet water is usually mint flavored",False]
  ["Reindeer like to eat bananas",True]
  ["A jellyfish is 95 percent water",True]
  ["An ostrich's eye is bigger than its brain",True]
  ["A cow produces 200 times more gas a day than a person",True]
  ["Chewing gum while peeling onions will keep you from crying",True]
  ["The only sound that doesn't echo is a duck's quack",True]
  ["The dinosaurs were killed off by a series of aliens attacking the earth",False]
  ["Chocolate never goes bad",False]
  ["During your lifetime, you'll eat about 60,000 pounds of food",True]
  ["12 newborns will be given to the wrong parents daily",True]
  ["Cat fur is an ice cream flavor in China",False]
  ["A fossil, believed to be of a unicorn was discovered in Scotland around 1950",False]
  ["Eating cupcakes burns calories",False]
  ["The oldest person to ever live was a cyborg Japanese woman who lived to be 160 years old",False]
  ["A jumbo jet uses 4,000 gallons of fuel to take off",True]
  ["Humans have 4 distinct zones on their tongue to perceive bitter, sour, salty, and sweet flavor",False]
  ["When the Cubs last won the world series, women did not have the right to vote in the United States",True]
  ["A penny dropped from a skyscraper could crack a skull",False]
  ["Men think about sex every 7-10 minutes",False]
  ["People swallow an average of 8 spiders a year in their sleep",False]
  ["Earth would be uninhabitable if it shifted 1 foot closer to the sun",False]
  ["The closest US state to Africa is Maine",True]
  ["Gum takes 7 years to pass through your body",False]
  ["Humans only use 10% of their brain",False]
  ["Pineapples grow from plants out of the ground",True]

  
]
console.log(thing);
